name: CICD Pipeline - Par2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-cd:

    runs-on: ubuntu-latest

    steps:
    - name: VersionControl
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build adn Package with Maven
      run: mvn -B celan compile package --file pom.xml

 
